//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHotel
    {
        public int IdBookingHotel { get; set; }
        public Nullable<int> accountID { get; set; }
        public Nullable<int> IdHotel { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<decimal> RoomPrice { get; set; }
        public Nullable<int> RoomCount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
