//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DAPMLThuyetEntities : DbContext
    {
        public DAPMLThuyetEntities()
            : base("name=DAPMLThuyetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<Airline> Airlines { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingHotel> BookingHotels { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<MoMoPayment> MoMoPayments { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
    
        public virtual ObjectResult<TTChuyenBay_Result> TTChuyenBay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTChuyenBay_Result>("TTChuyenBay");
        }
    
        public virtual ObjectResult<TTKhachSan_Result> TTKhachSan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTKhachSan_Result>("TTKhachSan");
        }
    
        public virtual ObjectResult<TTTaiKhoan_Result> TTTaiKhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TTTaiKhoan_Result>("TTTaiKhoan");
        }
    }
}
